### ISSUE TITLE
Obsidian becomes unresponsive when no timeMin or timeMax value is specified.

### ISSUE THREAD

**Issue by Oneechan69** [dexin-qi/obsidian-sync-calendar#7]
When I take the sample block from the readme:

````
```sync-calendar
name: "{numberTodos} todos @ Apr. 21"
timeMin: "2023-04-21"
timeMax: "2023-04-22"
```
````

And change it to this and let it render:
````
```sync-calendar
name: "{numberTodos} todos @ Apr. 21"
```
````

Obsidian becomes unresponsive, even after restarting. It goes away when I move or delete the plugin folder. Here's is some system information of that helps:
* macOS 13.1.
* Obsidian 1.2.8 (it also froze in 1.2.7).
* Plugin version 1.1.3.

**Comment by dustinksi** [comment]
Sorry for the confusion, but I'm unable to reproduce the issue you reported. The latest version of the plugin appears to be working properly for me.

https://github.com/dustinksi/obsidian-sync-calendar/assets/20951128/2cd8f1f7-33e4-4bcd-aff5-fef9e709ee25

A few suggestions to help resolve this:
1. Please double-check that you are running the latest release of the plugin. If not, try updating to the latest version and see if that fixes the problem.
2. As an alternative, you can enable "**Debug Logging**" for the plugin. This will output logs that may help locate where the problem is occurring. Please enable logging and send me the logs, so I can better diagnose what's going wrong.

Please let me know if any of these options help resolve the issue. I apologize for the inconvenience and will do my best to get to the bottom of this and push out any necessary fixes. Please feel free to ask me for any additional details or let me know if there's any other way I can assist you in troubleshooting this.
